name: MkDocs Deploy
on:
  push:
    branches:
      - main

env:
  FUSION_VERSION: 0.1

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install MkDocs
        run: pip install mkdocs-material==8.2.13

      - name: Install mike
        run: pip install mike==1.1.2

      - name: Configure FusionDoc Git user
        run: |
          git config user.name fusiondoc
          git config user.email fusiondoc@example.com

      - name: Fetch gh-pages branch
        run: git fetch origin gh-pages --depth=1

      - name: Deploy documentation
        run: mike deploy $FUSION_VERSION latest -u -b gh-pages -p

      - run: ls .
